[package]
name = "serial-ports"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread", "time"] }
tokio-serial = "5.4.5"
